//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// positioncontrol.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_POSITION_CONTROL_DIALOG     102
#define IDD_analysisDlg                 103
#define IDD_cameralistDlg               104
#define IDD_CameraControl               105
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       131
#define IDC_EDIT1                       1000
#define Edit_Log                        1000
#define IDC_BUTTON1                     1001
#define B_ROI_Reset                     1001
#define Button_Start                    1001
#define IDC_reload                      1001
#define IDC_CHECK1                      1002
#define CB_Da_Enable                    1002
#define B_ROI_Reset2                    1003
#define B_ROI_Reset_after               1003
#define IDC_BUTTON3                     1004
#define B_Capture                       1004
#define B_Rec_Start                     1005
#define Text_Camera_Control             1006
#define B_Record_Reset                  1006
#define IDC_BUTTON2                     1007
#define B_Rec_End                       1007
#define B_clear                         1007
#define Slider_Exposure_Cam1            1008
#define B_start                         1008
#define Text_exp_cam1                   1009
#define Text_Gain_Cam1                  1010
#define Text_Framerate_Cam1             1011
#define Slider_Gain_Cam1                1012
#define Slider_Framerate_Cam1           1013
#define B_Rec_Start2                    1014
#define Edit_Exposure_Cam1              1015
#define Edit_Gain_Cam1                  1016
#define IDC_EDIT4                       1017
#define Edit_Framerate_Cam1             1017
#define Slider_Th_Cam1                  1018
#define Slider_Th1_Cam1                 1018
#define Text_exp_cam2                   1018
#define Text_Th_Cam1                    1019
#define Text_Gain_Cam2                  1019
#define Edit_Th_Cam1                    1020
#define Edit_Th1_Cam1                   1020
#define Text_Framerate_Cam2             1020
#define Area_Camera_Control             1022
#define Area_Record                     1023
#define Area_DaBoard                    1024
#define Proportion                      1025
#define Derivation                      1026
#define Integral                        1027
#define Edit_Kp                         1028
#define Edit_Kd                         1029
#define Edit_Ki                         1030
#define Combo_Da                        1031
#define Text_TargetAngle                1032
#define IDC_EDIT2                       1033
#define Edit_Target_Angle               1033
#define Area_Log                        1034
#define Proportion2                     1035
#define Text_PrecAngle                  1036
#define IDC_EDIT3                       1037
#define Edit_Precision                  1037
#define Text_deg                        1038
#define Text_deg2                       1039
#define Text_ms                         1040
#define Text_ms2                        1041
#define Text_Record_Frame               1042
#define Text_ms3                        1042
#define Text_Save_Frame                 1043
#define Text_ms4                        1043
#define Text_TargetAngle2               1044
#define Text_Record_num                 1045
#define Text_Saved_num                  1046
#define Area_Position_Control           1047
#define Text_MaxVoltage                 1048
#define Text_MinVoltage                 1049
#define Edit_MaxVoltage                 1050
#define Edit_MinVoltage                 1051
#define Text_Frequency                  1052
#define Edit_Frequency                  1053
#define Text_Hz                         1054
#define Text_V                          1055
#define Text_V2                         1056
#define Edit_Target_Angle2              1057
#define CB_X_axis                       1058
#define IDC_CHECK3                      1059
#define CB_Y_axis                       1059
#define Browse_Box                      1060
#define Now_Angle                       1061
#define Text_NowAngle                   1062
#define Text_deg3                       1063
#define Slider_Exposure_Cam2            1064
#define Slider_Framerate_Cam2           1065
#define Slider_Gain_Cam2                1066
#define Slider_Th1_Cam2                 1067
#define Slider_Th2_Cam2                 1068
#define Text_PrecAngle2                 1069
#define Slider_Th2_Cam1                 1070
#define Edit_Th2_Cam1                   1071
#define Edit_Exposure_Cam2              1072
#define Edit_Gain_Cam2                  1073
#define Edit_Framerate_Cam2             1074
#define Edit_Th1_Cam2                   1075
#define Edit_Th2_Cam2                   1076
#define Edit_Precision2                 1077
#define IDC_BUTTON4                     1078
#define B_ROI_Reset_Cam2                1078
#define Text_deg4                       1079
#define Text_deg5                       1080
#define Now_Angle2                      1081
#define Text_NowAngle2                  1082
#define Text_deg6                       1083
#define Derivation2                     1084
#define Radio_Horizontal                1085
#define IDC_RADIO3                      1086
#define Radio_Vertical                  1086
#define Integral2                       1087
#define Edit_Kp_Ver                     1088
#define Edit_Kd_Ver                     1089
#define Edit_Ki2                        1090
#define Edit_Ki_Ver                     1090
#define CB_CCW                          1091
#define Text_Save_Frame2                1092
#define Text_Saved_num2                 1093
#define analysis                        1094
#define Browse_Box2                     1095
#define Slider_Th1_after                1098
#define Slider_Th2_after                1099
#define Edit_Th1_after                  1100
#define Edit_Th2_after                  1101
#define Text_Th1_after                  1102
#define Text_Th2_after                  1103
#define IDC_camlist                     1112
#define IDC_TEXT_BOTTOM                 1122
#define IDC_TEXT_SIDE                   1123
#define IDC_COMBO1                      1124
#define IDC_TEXT_ERORR                  1125
#define IDC_COMBO2                      1126
#define Combo                           1126
#define Combo_mode                      1126
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_end                          32774
#define ID_32775                        32775
#define ID_analysis                     32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_opencamlist                  32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
